//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Session3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrival
    {
        public int arrivalId { get; set; }
        public string userIdFK { get; set; }
        public System.DateTime arrivalDate { get; set; }
        public string arrivalTime { get; set; }
        public int numberHead { get; set; }
        public int numberDelegate { get; set; }
        public int numberCompetitors { get; set; }
        public int numberCars { get; set; }
        public int number19seat { get; set; }
        public int number42seat { get; set; }
    
        public virtual User User { get; set; }
    }
}
